name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the OS for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Step to check out your repository code

    - name: Configure AWS CLI
      run: |
        # Install jq if not already installed
        sudo apt-get install jq

    - name: Get Secrets from Secrets Manager
      id: get-secrets
      run: |
        # Fetch secrets from Secrets Manager
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id github/s3-credentials --query SecretString --output text)
        
        # Parse the JSON and set them as environment variables
        echo "$SECRET_JSON" | jq -r '. | to_entries | .[] | "\(.key)=\(.value)"' | xargs -0 -n1 echo >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}  # Access Key from Secrets Manager
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}  # Secret Key from Secrets Manager
        aws-region: us-west-2  # Specify your AWS region

    - name: Sync files to S3
      run: |
        # Sync files from the repository to the S3 bucket
        aws s3 sync ./local-folder s3://${{ env.S3_BUCKET }} --delete
